from testing import *
from numojo.linalg import Mat


# Comparison values generated by splitmix.c
def test_mat_init_w_value():
    var x = Mat[3, 3](2)
    for i in range(3):
        for j in range(3):
            assert_equal(x[i, j], 2)


def test_mat_get_set_item():
    var x = Mat[8, 8](0)
    for i in range(len(x)):
        x[i] = 2 / 3
        assert_equal(x[i], 2 / 3)
    for i in range(x.rows):
        for j in range(x.cols):
            x[i, j] = 1 / 3
            assert_equal(x[i, j], 1 / 3)
    with assert_raises():
        _ = x[-1]
    with assert_raises():
        _ = x[100]
    with assert_raises():
        _ = x[-1, 1]
    with assert_raises():
        _ = x[100, 2]
    with assert_raises():
        _ = x[1, -1]
    with assert_raises():
        _ = x[2, 100]


def test_get_row_col():
    var x = Mat[3, 5](1)
    var r = x.get_row(1)
    var c = x.get_col(4)
    assert_equal(r.rows, 1)
    assert_equal(r.cols, 5)
    assert_equal(c.rows, 3)
    assert_equal(c.cols, 1)
    for i in range(len(r)):
        assert_equal(r[i], 1)
    for i in range(len(c)):
        assert_equal(c[i], 1)
    with assert_raises():
        _ = x.get_row(-1)
    with assert_raises():
        _ = x.get_row(10)
    with assert_raises():
        _ = x.get_col(-1)
    with assert_raises():
        _ = x.get_col(10)
