from testing import *
from numojo.xoroshiro import *


# Comparison values generated by xoroshiro128p.c
def test_xoroshiro128plus():
    var rng = Xoroshiro128plus(123456789)
    assert_equal(rng.next(), 11299058612650730663)
    rng.jump()
    assert_equal(rng.next(), 10930983919389870347)
    rng.long_jump()
    assert_equal(rng.next(), 4581129002071406998)


def test_xoroshiro128plusplus():
    var rng = Xoroshiro128plusplus(123456789)
    assert_equal(rng.next(), 14276238831215357973)
    rng.jump()
    assert_equal(rng.next(), 12069649097727364570)
    rng.long_jump()
    assert_equal(rng.next(), 7355498414224595376)


def test_xoroshiro128starstar():
    var rng = Xoroshiro128starstar(123456789)
    assert_equal(rng.next(), 5784055621119223165)
    rng.jump()
    assert_equal(rng.next(), 13092379945252257135)
    rng.long_jump()
    assert_equal(rng.next(), 12365686216782178100)
