from testing import *
from stochasticity.splitmix import SplitMix


# Comparison values generated by splitmix.c
def test_splitmix():
    var rng = SplitMix(123456789, 1000)
    assert_equal(rng.next(), 3755887478024829079)
    assert_equal(rng.next(), 7844710984108051227)
    assert_equal(rng.next(), 15507083960855181607)
