from testing import *
from numojo.xoshiro import *


# Comparison values generated by xoroshiro128p.c
def test_xoshiro256plus():
    var rng = Xoshiro256plus(123456789)
    assert_equal(rng.next(), 12059086120572499294)
    rng.jump()
    assert_equal(rng.next(), 6473535184725534191)
    rng.long_jump()
    assert_equal(rng.next(), 12794950360312403446)


def test_xoshiro256plusplus():
    var rng = Xoshiro256plusplus(123456789)
    assert_equal(rng.next(), 11089759438045651894)
    rng.jump()
    assert_equal(rng.next(), 66056455977260917)
    rng.long_jump()
    assert_equal(rng.next(), 3938992559361620932)


def test_xoshiro256starstar():
    var rng = Xoshiro256starstar(123456789)
    assert_equal(rng.next(), 15127205273500847298)
    rng.jump()
    assert_equal(rng.next(), 14782342367199966867)
    rng.long_jump()
    assert_equal(rng.next(), 4400463616481334238)
