from testing import *
from numojo.splitmix import SplitMix


# Comparison values generated by splitmix.c
def test_splitmix():
    var rng = SplitMix(123456789)
    assert_equal(rng.next(), 2466975172287755897)
    assert_equal(rng.next(), 8832083440362974766)
    assert_equal(rng.next(), 3534771765162737125)
